using Microsoft.AspNetCore.Mvc;
using SimpleApi.Models;
using SimpleApi.Services;
using System.Text;

namespace SimpleApi.Controllers;

[ApiController]
[Route("api/[controller]")]
[Produces("application/json")]
public class TranscriptController : ControllerBase
{
    private readonly ILogger<TranscriptController> _logger;
    private readonly EmailService _emailService;
    private readonly SummaryService _summaryService;

    public TranscriptController(ILogger<TranscriptController> logger, EmailService emailService, SummaryService summaryService)
    {
        _logger = logger;
        _emailService = emailService;
        _summaryService = summaryService;
    }

    [HttpPost("send")]
    [ProducesResponseType(typeof(ApiResponse<object>), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ApiResponse<object>), StatusCodes.Status400BadRequest)]
    public async Task<IActionResult> SendTranscript([FromBody] TranscriptRequest request)
    {
        if (!ModelState.IsValid)
        {
            _logger.LogWarning("Invalid transcript request");
            var errors = ModelState.Values
                .SelectMany(v => v.Errors)
                .Select(e => e.ErrorMessage)
                .ToList();
            return BadRequest(ApiResponse<object>.Error(errors, "Validation failed"));
        }

        try
        {
            _logger.LogInformation("Sending transcript summary for room {RoomName} to {Email}",
                request.RoomName, request.To);

            // Convert transcript messages to the format expected by SummaryService
            var conversationMessages = request.Transcript.Messages
                .Select(m => new Services.ConversationMessage
                {
                    Role = m.Role,
                    Text = m.Text,
                    Timestamp = m.Timestamp
                })
                .ToList();

            // Generate AI-powered summary
            var emailBody = await _summaryService.SummarizeConversationAsync(conversationMessages, request.RoomName);

            // Send email using EmailService
            var subject = $"Conversation Summary - {request.RoomName}";
            var emailSent = await _emailService.SendEmailAsync(request.To, subject, emailBody);

            if (!emailSent)
            {
                _logger.LogError("Failed to send email to {Email}", request.To);
                return StatusCode(500, ApiResponse<object>.Error("Failed to send transcript email"));
            }

            return Ok(ApiResponse<object>.Ok(
                new { sentAt = DateTime.UtcNow },
                "Transcript summary sent successfully"
            ));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error sending transcript");
            return StatusCode(500, ApiResponse<object>.Error("Failed to send transcript"));
        }
    }

    private string FormatTranscriptEmail(TranscriptRequest request)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"<html><body style='font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;'>");
        sb.AppendLine($"<h2 style='color: #6EE7B7;'>Voice Agent Conversation Transcript</h2>");
        sb.AppendLine($"<p><strong>Room:</strong> {request.RoomName}</p>");

        if (request.Transcript.Metadata != null)
        {
            sb.AppendLine($"<p><strong>Start:</strong> {request.Transcript.Metadata.ConversationStart}</p>");
            sb.AppendLine($"<p><strong>End:</strong> {request.Transcript.Metadata.ConversationEnd}</p>");
            sb.AppendLine($"<p><strong>Total Messages:</strong> {request.Transcript.Metadata.TotalMessages}</p>");
        }

        sb.AppendLine("<hr style='margin: 20px 0; border: 1px solid #e0e0e0;' />");
        sb.AppendLine("<div style='background: #f9fafb; padding: 20px; border-radius: 8px;'>");

        foreach (var msg in request.Transcript.Messages)
        {
            var isUser = msg.Role == "user";
            var bgColor = isUser ? "#667eea" : "#6EE7B7";
            var textColor = isUser ? "white" : "#0a1628";
            var align = isUser ? "right" : "left";

            sb.AppendLine($"<div style='margin: 10px 0; text-align: {align};'>");
            sb.AppendLine($"<div style='display: inline-block; max-width: 75%; padding: 12px 16px; background: {bgColor}; color: {textColor}; border-radius: 16px; text-align: left;'>");
            sb.AppendLine($"<p style='margin: 0;'>{msg.Text}</p>");
            sb.AppendLine($"<small style='opacity: 0.7;'>{msg.Timestamp}</small>");
            sb.AppendLine("</div></div>");
        }

        sb.AppendLine("</div>");
        sb.AppendLine("<p style='margin-top: 20px; color: #9ca3af; font-size: 12px;'>Generated by Prepreater & Co. Voice Agent</p>");
        sb.AppendLine("</body></html>");

        return sb.ToString();
    }
}
